# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is in the Cinema?'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name="Movie's name"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Studio\\s name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=120, verbose_name='Movie\\s year film'),
        ),
    ]
