# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20180217_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(blank=True, max_length=120, validators=[movie.validators.validate_studioname], verbose_name='Studio\\s name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=120, validators=[movie.validators.validate_yearfilms], verbose_name='Movie\\s year film'),
        ),
    ]
