# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20180217_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('drama', 'Drama'), ('adventure', 'Adventure')], default='action', max_length=120),
        ),
    ]
